In [1]:
# Import Libraries

import numpy as np
import time
from sklearn.datasets import load_iris

In [2]:
# Load Iris Dataset

iris = load_iris()

data = iris.data

feature_names = iris.feature_names

print("Dataset Shape:", data.shape)

print("\nFeature Names:")
print(feature_names)

print("\nFirst 5 Rows:")
print(data[:5])

Dataset Shape: (150, 4)

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

First 5 Rows:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
# Array Creation

array1 = np.array([1, 2, 3, 4, 5])

zeros_array = np.zeros((2, 3))

ones_array = np.ones((3, 3))

random_array = np.random.rand(2, 2)

print("1D Array:")
print(array1)

print("\nZeros Array:")
print(zeros_array)

print("\nOnes Array:")
print(ones_array)

print("\nRandom Array:")
print(random_array)

1D Array:
[1 2 3 4 5]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random Array:
[[0.88012484 0.9478329 ]
 [0.14811839 0.72120985]]


In [4]:
# Indexing and Slicing

print("First Row:")
print(data[0])

print("\nFirst Column:")
print(data[:, 0])

print("\nFirst 10 Rows:")
print(data[:10])

print("\nRows 10 to 20 and Columns 1 to 3:")
print(data[10:20, 1:3])

First Row:
[5.1 3.5 1.4 0.2]

First Column:
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]

First 10 Rows:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Rows 10 to 20 and Columns 1 to 3:
[[3.7 1.5]
 [3.4 1.6]
 [3.  1.4]
 [3.  1.1]
 [4.  1.2]
 [4.4 1.5]
 [3.9 1.3]
 [3.5 1.4]
 [3.8 1.7]
 [3.8 

In [5]:
# Mathematical Operations

addition = data + 2

multiplication = data * 2

square = np.square(data)

print("Addition:")
print(addition[:3])

print("\nMultiplication:")
print(multiplication[:3])

print("\nSquare:")
print(square[:3])

Addition:
[[7.1 5.5 3.4 2.2]
 [6.9 5.  3.4 2.2]
 [6.7 5.2 3.3 2.2]]

Multiplication:
[[10.2  7.   2.8  0.4]
 [ 9.8  6.   2.8  0.4]
 [ 9.4  6.4  2.6  0.4]]

Square:
[[26.01 12.25  1.96  0.04]
 [24.01  9.    1.96  0.04]
 [22.09 10.24  1.69  0.04]]


In [6]:
# Axis-wise Operations

column_mean = np.mean(data, axis=0)

row_sum = np.sum(data, axis=1)

column_max = np.max(data, axis=0)

print("Mean of Columns:")
print(column_mean)

print("\nSum of Rows:")
print(row_sum[:10])

print("\nMaximum Values:")
print(column_max)

Mean of Columns:
[5.84333333 3.05733333 3.758      1.19933333]

Sum of Rows:
[10.2  9.5  9.4  9.4 10.2 11.4  9.7 10.1  8.9  9.6]

Maximum Values:
[7.9 4.4 6.9 2.5]


In [7]:
# Statistical Operations

mean = np.mean(data)

median = np.median(data)

std_dev = np.std(data)

minimum = np.min(data)

maximum = np.max(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Minimum:", minimum)
print("Maximum:", maximum)

Mean: 3.4644999999999997
Median: 3.2
Standard Deviation: 1.9738430577598278
Minimum: 0.1
Maximum: 7.9


In [8]:
# Reshaping Arrays

reshaped = array1.reshape((5, 1))

flattened = reshaped.flatten()

print("Reshaped Array:")
print(reshaped)

print("\nFlattened Array:")
print(flattened)

Reshaped Array:
[[1]
 [2]
 [3]
 [4]
 [5]]

Flattened Array:
[1 2 3 4 5]


In [9]:
# Broadcasting

broadcast_result = data + np.array([1, 1, 1, 1])

print("Broadcasted Result:")
print(broadcast_result[:5])

Broadcasted Result:
[[6.1 4.5 2.4 1.2]
 [5.9 4.  2.4 1.2]
 [5.7 4.2 2.3 1.2]
 [5.6 4.1 2.5 1.2]
 [6.  4.6 2.4 1.2]]


In [10]:
# Save and Load Arrays

np.save("iris_data.npy", data)

loaded_data = np.load("iris_data.npy")

print("Loaded Data Shape:")
print(loaded_data.shape)

Loaded Data Shape:
(150, 4)


In [11]:
# Performance Comparison

python_list = list(range(1000000))

numpy_array = np.arange(1000000)

# Python List Timing
start = time.time()

python_result = [x * 2 for x in python_list]

end = time.time()

print("Python List Time:", end - start)

# NumPy Timing
start = time.time()

numpy_result = numpy_array * 2

end = time.time()

print("NumPy Array Time:", end - start)

Python List Time: 0.05299997329711914
NumPy Array Time: 0.004071712493896484


In [12]:
print("NUMPY DATA EXPLORER PROJECT COMPLETED")

NUMPY DATA EXPLORER PROJECT COMPLETED
